// constants
import c from './constants';

export const FETCH_LIST_LINES = `${c}/FETCH_LIST_LINES`;
export const FETCH_LIST_LINES_SUCCESS = `${c}/FETCH_LIST_LINES_SUCCESS`;
export const FETCH_INFO_LINE = `${c}/FETCH_INFO_LINE`;
export const FETCH_INFO_LINE_SUCCESS = `${c}/FETCH_INFO_LINE_SUCCESS`;
export const FETCH_DIRECTION_LINE = `${c}/FETCH_DIRECTION_LINE`;
export const FETCH_DIRECTION_LINE_SUCCESS = `${c}/FETCH_DIRECTION_LINE_SUCCESS`;
export const SAVE_FAVORITE = `${c}/SAVE_FAVORITE`;
export const SAVE_FAVORITE_SUCCESS = `${c}/SAVE_FAVORITE_SUCCESS`;
export const GET_FAVORITES = `${c}/GET_FAVORITES`;
export const GET_FAVORITES_SUCCESS = `${c}/GET_FAVORITES_SUCCESS`;
export const LOAD_FAVORITES = `${c}/LOAD_FAVORITES`;
export const LOAD_FAVORITES_SUCCESS = `${c}/LOAD_FAVORITES_SUCCESS`;
export const ADD_FAVORITE = `${c}/ADD_FAVORITE`;
export const ADD_FAVORITE_SUCCESS = `${c}/ADD_FAVORITE_SUCCESS`;
export const DELETE_FAVORITE = `${c}/DELETE_FAVORITE`;
export const DELETE_FAVORITE_SUCCESS = `${c}/DELETE_FAVORITE_SUCCESS`;
export const FETCH_BUS_STOP = `${c}/FETCH_BUS_STOP`;
export const FETCH_BUS_STOP_SUCCESS = `${c}/FETCH_BUS_STOP_SUCCESS`;
export const FETCH_BUS_STOP_ERROR = `${c}/FETCH_BUS_STOP_ERROR`;
export const FETCH_BUS_STOP_TIMES = `${c}/FETCH_BUS_STOP_TIMES`;
export const FETCH_BUS_STOP_TIMES_SUCCESS = `${c}/FETCH_BUS_STOP_TIMES_SUCCESS`;
export const FETCH_BUS_STOP_TIMES_ERROR = `${c}/FETCH_BUS_STOP_TIMES_ERROR`;
export const LOGIN_EMT = `${c}/LOGIN_EMT`;
export const LOGIN_EMT_SUCCESS = `${c}/LOGIN_EMT_SUCCESS`;
export const FILTER_LINES_BY_CRITERIAL = `${c}/FILTER_LINES_BY_CRITERIAL`;
